global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_match:
  - severity = critical
  target_match_re:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_match:
  - severity = warning
  target_match_re:
  - severity = info
- equal:
  - namespace
  source_match:
  - alertname = InfoInhibitor
  target_match_re:
  - severity = info
- target_match_re:
  - alertname = InfoInhibitor
receivers:
- name: "null"
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: Watchdog
  - matchers:
    - severity="critical|warning|info"
    - namespace!="dev|ci"
    receiver: Critical
templates:
- /etc/alertmanager/config/*.tmpl
